import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import NavBar from "@/components/layout/NavBar";
import Container from "@/components/Container";
import { Toaster } from "@/components/ui/toaster";
import {SessionProvider} from "next-auth/react";

export const metadata: Metadata = {
    title: "Online booking",
    description: "Generated by M.K.",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <SessionProvider>
            <html lang="en" suppressHydrationWarning>
            <body className={GeistSans.className}>
            <div className="min-h-screen flex flex-col bg-secondary">
                <NavBar />
                <main className="flex-grow relative">
                    <Container>
                        <div className="main-content">
                            {children}
                        </div>
                    </Container>
                </main>
            </div>
            <Toaster />
            </body>
            </html>
        </SessionProvider>
    );
}