import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import NavBar from "@/components/layout/NavBar";
import Container from "@/components/Container";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
    title: "Online booking",
    description: "Generated by M.K.",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider dynamic={true}>
            <html lang="en" suppressHydrationWarning>
            <body className={GeistSans.className}>
            <main className="flex flex-col min-h-screen bg-secondary">
                <NavBar />
                <section className="flex-grow">
                    <Container>
                        {children}
                    </Container>
                </section>
            </main>
            <Toaster />
            </body>
            </html>
        </ClerkProvider>
    );
}